### ISSUE TITLE
DropDown with treeview and custom input - space not working

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#29]
It is not possible to add a white space to the input field in the DropDown control if the picker control being used is TreeView, because Spacebar is used to toggle selections. The following snippet demonstrates the problem:
https://jsfiddle.net/72q6torz/

The toggle behaviour should be suppressed when the input field is not empty.

**Comment by Jemt** [comment]
Work around: It works when the DropDown menu is closed, so simply close it programmatically when someone is typing:

```
dropdown.OnInputChanged(function(sender, value)
{
	dropdown.CloseDropDown();
});
```

Changing label from 'bug' to 'minor bug'

**Comment by FlowIT-JIT** [comment]
The problem is here:

![image](https://user-images.githubusercontent.com/10479064/49800669-5e844700-fd48-11e8-9fc3-8742e0e97d61.png)

Our best option is probably to filter the events so that only certain events are passed to the picker control:

![image](https://user-images.githubusercontent.com/10479064/49800805-c2a70b00-fd48-11e8-95e0-a6dff5c4ed1f.png)

Obviously this is not ideal. It cripples the picker which can no only react when the user uses the arrow keys and the spacebar button.

**Comment by FlowIT-JIT** [comment]
Based on the observations it seems the implementation found in WSDropDown is the best solution. When the user enters text the picker switches to a flat list view instead where selection is possible using the ENTER key.

IF a developer wants to use text search with a TreeView as a picker, the best option is to use the [work around suggested June 23 2018](https://github.com/Jemt/Fit.UI/issues/29#issuecomment-399681607).
