### ISSUE TITLE
DropDown Boundary Detection: Open above control and resize height if necessary

### ISSUE THREAD

**Issue by FlowIT-JIT** [Jemt/Fit.UI#41]
DropDown should open menu above itself if sufficient space is not available below control.
If sufficient space is not available above control either, determine whether most space is available above or below control, resize menu height to make it fit, and position menu where appropriate.

![image](https://user-images.githubusercontent.com/10479064/43634299-05422aa6-970c-11e8-89dd-2e88c1c5000b.png)

Code: https://github.com/Jemt/Fit.UI/blob/master/Controls/DropDown/DropDown.js#L1235

Repositioning is possible using margin-top with a negative margin (see screenshot above).

Make sure behaviour can be enabled/disabled - it should be On by default.

Note to self: It should probably be disabled in CF if hosted within a frame to avoid breaking "overflow boundaries". Something like:

```
var isFramed = (window.parent !== window);
dropdown.DetectBoundaries(isFramed === false);
```

**Comment by Jemt** [comment]
It's actually a bit more complicated since the drop down menu may adjust its height based on its content. So for instance a TreeView picker might increase the height of the menu when tree nodes are expanded. So we should probably prevent resizing in the case where sufficient space is not available - or, if sufficient spacing is available above the control, make sure increasing the size does not affect positioning.

**Comment by FlowIT-JIT** [comment]
Use this JSFiddle to test:
https://jsfiddle.net/eutfbk26/

**Comment by FlowIT-JIT** [comment]
Fixed: https://github.com/Jemt/Fit.UI/commit/75f95c57cda75ccec201fcaffcf4a2cc86499929
Available in NPM package v. 1.3.2+

**Comment by FlowIT-JIT** [comment]
Tested with IE8, IE10, Edge16, Firefox 62.0.3, and Chrome 69.0.3497.100.
Closing issue.

**Comment by FlowIT-JIT** [comment]
Updated JSFiddle:
https://jsfiddle.net/eutfbk26/1/
