### ISSUE TITLE
Template - two situations where controls cannot be disposed

### ISSUE THREAD

**Issue by FlowIT-JIT** [Jemt/Fit.UI#45]
Consider the following example:

```
var t = new Fit.Template();
t.LoadHtml("{MyControl}");
t.Content.MyControl = new Fit.Controls.Input();
t.Render(document.body);
```

If we want to get rid of the template above, there is no way of disposing it.
Fit.Template.Dispose() is missing!

Also, consider this example:

```
var t = new Fit.Template(true); // True = allow updates
t.LoadHtml("{[MyControl]}");
t.Content.MyControl = new Fit.Controls.Input();
t.Render(document.body);

t.Content.MyControl = null;
t.Update();
```

MyControl is not disposed when calling Update() since Render() did not store the control internally to allow Update to get rid of it again.

Work around for second example:
1) Render template before populating it
2) Populate with controls and call Update
3) Clear data and call Update again to trigger autoDispose.

**Comment by Jemt** [comment]
1. Make toString functions add elements to `pendingElements` rather than `elements`
2. Make Render and Update move `pendingElements` to `elements`
3. Make Render store controls in `controls`
4. Implement Dispose function that calls Fit.Dom.Remove(..) on everything in `elements` and calls Dispose() on everything in `controls`
