### ISSUE TITLE
Add support for ControlBase.Disabled(..)

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#6]
Being able to disable a control seems rather fundamental, so we need to implement such functionality on ControlBase. Until implemented the work around below may be helpful to some.

```
(function()
{
    var dd = Fit.Controls.Find("DropDown1");
    var val = dd.Value();
    var dom = dd.GetDomElement();
    Fit.Events.AddHandler(dom, "click", true, function(e) { Fit.Events.StopPropagation(e); });
    Fit.Events.AddHandler(dom, "mousedown", true, function(e) { Fit.Events.StopPropagation(e); });
    Fit.Events.AddHandler(dom, "mouseup", true, function(e) { Fit.Events.StopPropagation(e); });
    Fit.Array.ForEach(dom.querySelectorAll("input"), function(inp) { inp.setAttribute("tabindex", "-1"); });
    dd.OnChange(function(sender) { if (dd.Value() !== val) dd.Value(val); });
    dom.style.opacity = "0.5";
})();
```

**Comment by FlowIT-JIT** [comment]
A general solution working for all controls must take several things into account:

1) Should we be able to interact with control to e.g. copy text ?
2) Should the control remain part of tab flow ?
3) Make sure it works when data is loaded async and introduces focusable elements in a control (e.g. items in a DropDown or nodes in a TreeView).

**Comment by FlowIT-JIT** [comment]
Standard HTML controls vary in behaviour.
- A disabled input field allows for text selection.
- A disabled dropdown control cannot be opened to reveal available options.
- A disabled datepicker control cannot be opened to reveal the calendar widget, and it doesn't allow the user to select and copy the value like the input field does.
- A textarea allows for text selection, but also allow interaction; the user can resize the control.

It seems to best approach would be to disable user interaction but allow text selection where it makes sense - mostly in input-based controls.

**Comment by FlowIT-JIT** [comment]
Note to self: Remember that tab flow is tricky!
elm.tabIndex returns -1 for non-focusable elements.
elm.tabIndex = -1; makes the element focusable (sigh!) and adds the tabindex="-1" attribute.
elm.tabIndex = 0; makes the element focusable and part of tab flow.
The only way prevent the element from gaining focus now, is by removing the attribute: elm.removeAttribute("tabindex").
aLink.tabIndex returns 0 by default and _always_ receive focus when clicked - this can not be disabled, only hacked with an event handler removing focus again. A value of -1 takes it out of tab flow.

**Comment by FlowIT-JIT** [comment]
A general solution have been implemented on ControlBase: Enabled(bool).
The following controls and components implement their own version of Enabled though:
Button, CheckBox, FilePicker, and Input.

The general solution on ControlBase allow controls to inherit the ability to be disabled. But this approach relies on modifications to the control's DOM elements. This poses a minor problem if controls are populated _after_ the control has been disabled, since newly introduced DOM elements may accept focus via TAB navigation, and we do not want disabled controls to be part of the tab flow.
ControlBase handles this by returning focus to the previously focused element, if the control receives focus via TAB navigation. But it also re-initializes the disabled state so that newly introduced DOM elements are "disabled".
The user will experience this as the TAB key not "working". But pressing it yet again will make the focus skip the disabled control just like expected.
A warning is logged to make it clear what happend:

![image](https://user-images.githubusercontent.com/10479064/98407591-360a4200-2070-11eb-9ba2-99743826a895.png)

So, this is only a problem if the control is populated _after_ being disabled, and only when/if the user navigates through controls using the TAB key.

The solution to the problem mentioned is actually quite simple, although the performance implications are not clear yet, and it also requires specialized controls to know about ControlBase.Enabled's inner workings. But simply re-disabling the control will ensure that newly introduced DOM elements are disabled as well to prevent them from receiving focus - that's all it takes. Example implementations (which might not perform well with many operations or huge amounts of data):

DropDown (when selections are added - might be called many times):
![image](https://user-images.githubusercontent.com/10479064/98406782-dcedde80-206e-11eb-903d-ab241fa3efed.png)

WSTreeView (when data has been loaded and populated - could potentially be called multiple times):
![image](https://user-images.githubusercontent.com/10479064/98406882-06a70580-206f-11eb-8c81-ce7752477b27.png)

Something similar should be implemented for TreeView and WSDropDown.

It is not very likely to become an actual problem through. Most often data does not load until the control is triggered (e.g. WSDropDown), and in this case the data loaded and populated is not part of tab flow anyways since the objects are hidden within the pulldown menu. But if the TreeView or WSTreeView is used for navigation, it's a problem.
And if selections are added to a DropDown _after_ being disabled, it's a problem. But it's quite easy to make sure to disable the control _afterwards_ rather than _before_.
