### ISSUE TITLE
DropDown: horizontal scroll affects position of pulldown menu

### ISSUE THREAD

**Issue by FlowIT-JIT** [Jemt/Fit.UI#93]
See the following example:
https://jsfiddle.net/uy5nspfh/

Scrolling to the right affects the positioning of the pulldown menu when DetectBoundaries(true) has been set.

![image](https://user-images.githubusercontent.com/10479064/73063469-21710a80-3e9f-11ea-822e-138186173653.png)

**Comment by Jemt** [comment]
This issue has been addressed with the following commit: https://github.com/Jemt/Fit.UI/commit/95f30aa3c2f0a8d741e959d707991434d3fc089c

DropDown menu now uses position:absolute by default.
However, hosting the control in a container with _overflow_ may still trigger this behaviour since that case will make the control use position:fixed again, but that's as it's a fairly uncommon scenario. Downgrading to _minor bug_.

**Comment by FlowIT-JIT** [comment]
Fixed with the introduction of right side edge detection (see #96).

**Comment by FlowIT-JIT** [comment]
NOTICE: The JSFiddle demonstrating the problem uses the latest version of Fit.UI from the NPM registry (fit-ui@latest), so the problem can no longer be reproduced using these examples.
